services:
  - type: web
    name: react-app
    env: node
    buildCommand: npm run build
    startCommand: serve -s build
    routes:
      - type: rewrite
        source: "/**"
        destination: "/index.html"
