# Generated by Django 5.1.3 on 2024-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='botanical_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='plant_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='S', max_length=200),
        ),
    ]
